name: Test and Azure Deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install pytest pytest-asyncio httpx

      - name: Run tests
        run: |
          pytest tests/

  # build-and-deploy:
  #   needs: test
  #   runs-on: ubuntu-latest
  #   environment: production
    # if: github.ref == 'refs/heads/main'
    
  #   env:
  #     AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  #     AZURE_ENV_NAME: dance-monkey
  #     AZURE_LOCATION: eastus2
  #     AZURE_PRINCIPAL_ID: ${{ secrets.AZURE_PRINCIPAL_ID }}
  #     AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  #     AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  #     AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3

  #     - name: Install Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: '3.9'
  #         cache: 'pip'

  #     - name: Install azd
  #       run: |
  #         curl -fsSL https://aka.ms/install-azd.sh | bash

  #     - name: Azure login
  #       uses: azure/login@v1
  #       with:
  #         client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #     - name: Initialize azd
  #       run: |
  #         azd init --template dance-monkey

  #     - name: Set azd environment
  #       run: |
  #         azd env new ${{ env.AZURE_ENV_NAME }} --subscription ${{ env.AZURE_SUBSCRIPTION_ID }} --location ${{ env.AZURE_LOCATION }} --no-prompt

  #     - name: Azure Dev Deploy
  #       run: |
  #         azd config set auth.useAzCliAuth true
  #         azd up --no-prompt
  #       env:
  #         AZURE_ENV_NAME: ${{ env.AZURE_ENV_NAME }}
  #         AZURE_LOCATION: ${{ env.AZURE_LOCATION }}
  #         AZURE_SUBSCRIPTION_ID: ${{ env.AZURE_SUBSCRIPTION_ID }}
  #         AZURE_TENANT_ID: ${{ env.AZURE_TENANT_ID }}
  #         AZURE_PRINCIPAL_ID: ${{ env.AZURE_PRINCIPAL_ID }}